version: "3"
networks:
  server-connection:
    driver: bridge
services:
  server:
    container_name: server
    networks:
      - server-connection
    build:
      context: ./backend-web
      args:
        SERVER_MODE: prod
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
  client:
    container_name: client
    networks:
      - server-connection    
    build:
      context: ./frontend-web
    ports:
      - 3000:3000
    depends_on:
      - server
  nginx:
    container_name: nginx 
    image: nginx:alpine
    restart: always
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - client
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/cert
    ports:
      - 80:80
      - 443:443