spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 548066337721-rrr2sqadhaci94lbmsc5v171mme3pa8f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
            scope: email
          naver:
            client-id: GU8vMgpmm9GZ4AksoXdC
            client-secret: "mYeGMkaCo1"
            redirect-uri: http://localhost:8080/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
          kakao:
            client-id: 2677b72de7f0b9747b04f0d8bf994b94
            client-secret: FfAEmj03tAS25ETn4mnvDBrSYFWwV4WH
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # redis 연동
  data:
    redis:
      host: sonagi.site
      port: 6379

  # Maria DB 연동
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sonagi.site:50000/ssafy_b207
    username: ssafy-b207
    password: ssafy_b207_1

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      hibernate: info


# front - redirect uri
app:
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth/redirect

jwt:
  key: YourewaitingforatrainAtrainthatwilltakeyoufarawayYouknowwhereyouhope

# S3 setting
cloud:
  aws:
    s3:
      bucket: sonagi-application
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA6E5N5REX4NIVDL7A
      secretKey: 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

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ssafy
#    key-store-type: PKCS12
